name: Deploy Sphinx Documentation to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            graphviz \
            texlive-latex-base \
            texlive-fonts-recommended \
            texlive-fonts-extra \
            texlive-latex-extra

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Sphinx documentation
        run: |
          cd source
          make html
        env:
          SPHINXOPTS: "-W --keep-going"

      - name: Create .nojekyll file
        run: touch source/build/html/.nojekyll

      - name: Add custom domain (optional)
        run: |
          # Uncomment and modify if using custom domain
          # echo "your-domain.com" > source/build/html/CNAME

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: source/build/html

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./source/build/html
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy documentation: ${{ github.event.head_commit.message }}'

      - name: Notify on success
        if: success()
        run: |
          echo "✅ Documentation deployed successfully!"
          echo "🌐 View at: https://${{ github.repository_owner }}.github.io/$(basename ${{ github.repository }})"

      - name: Notify on failure
        if: failure()
        run: |
          echo "❌ Documentation deployment failed!"
          echo "Check logs for errors."
